name: LevelSystem
api: [4.0.0]
main: Laith98Dev\LevelSystem\Main
author: Laith98Dev
website: https://github.com/Laith98Dev
version: 1.0.1
description: Advanced LevelSystem for PocketMine-MP
depend: [PureChat, PurePerms, ScoreHud]

commands:
  ls:
    description: LevelSystem Command
    permission: levelsystem.command.staff

permissions:
  levelsystem.command.staff:
    default: op
